version: '3'

services:
  api:
    image: loot-manager-api:SNAPSHOT
    container_name: api
    build:
      context: .
    ports:
      - "5555:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      SA_PASSWORD: "Password#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"