version: '3'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      SA_PASSWORD: "Password#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    